'use strict';

const fs      = require('fs-extra');
const path    = require('path');
const chalk   = require('chalk');
const inquirer = require('inquirer');
const analyzer = require('../compiler/legacy-analyzer');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Print a section heading.
 * @param {string} text
 */
function heading(text) {
  console.log('\n' + chalk.bold.cyan(text));
}

/**
 * Print an indented info line.
 * @param {string} text
 */
function info(text) {
  console.log(chalk.gray('  ' + text));
}

/**
 * Print a success tick line.
 * @param {string} text
 */
function ok(text) {
  console.log(chalk.green('  ' + text));
}

/**
 * Print a warning line.
 * @param {string} text
 */
function warn(text) {
  console.log(chalk.yellow('  ' + text));
}

// ---------------------------------------------------------------------------
// MIGRATION.md generator
// ---------------------------------------------------------------------------

/**
 * Build the content of MIGRATION.md.
 *
 * @param {Object} report          — from legacy-analyzer.convert()
 * @param {string} sourceDir
 * @param {string} outputDir
 * @param {boolean} spa
 * @returns {string}
 */
function buildMigrationMd(report, sourceDir, outputDir, spa) {
  const date = new Date().toISOString().slice(0, 10);

  const frameworkWarnings = report.detected.frameworks.length > 0
    ? report.detected.frameworks.map(f =>
        `- **${f}**: The original site used ${f}. ` +
        `You may need to re-implement ${f}-specific behaviour using DYWO reactive data or native DOM APIs.`
      ).join('\n')
    : '- No external frameworks detected.';

  const buildSystemWarnings = report.buildSystems && report.buildSystems.length > 0
    ? `The following build-system configs were found in the source directory and have **not** been migrated:\n\n` +
      report.buildSystems.map(b => `- \`${b}\``).join('\n') +
      `\n\nReview them and migrate any custom transforms / aliases manually.`
    : 'No pre-existing build system was detected.';

  const eventHandlerSection = report.inlineEventHandlerPages.length > 0
    ? `The following pages contained inline event-handler attributes (e.g. \`onclick\`,\`onload\`) that have been moved into the component's \`mounted()\` hook:\n\n` +
      report.inlineEventHandlerPages.map(f => `- \`${f}\``).join('\n') +
      `\n\nReview each \`mounted()\` block and convert the statements to proper DYWO reactive methods where appropriate.`
    : 'No inline event handlers were detected.';

  const pageList   = report.writtenPages.map(f => `- \`${f}\``).join('\n');
  const compList   = report.writtenComponents.length > 0
    ? report.writtenComponents.map(f => `- \`${f}\``).join('\n')
    : '- No shared structural components were extracted.';

  return `# MIGRATION.md

> Generated by \`dywo migrate\` on ${date}

## What was migrated

| Item | Count |
|------|-------|
| HTML pages | ${report.pageCount} |
| CSS files | ${report.cssCount} |
| JS files | ${report.jsCount} |
| Assets copied | ${report.assetCount} |

**Source directory:** \`${sourceDir}\`
**Output directory:** \`${outputDir}\`
**Mode:** ${spa ? 'SPA (single-page application)' : 'MPA (multi-page)'}

---

## Generated pages

${pageList || '- None'}

## Generated shared components

${compList}

---

## Detected frameworks — manual attention required

${frameworkWarnings}

---

## Existing build system

${buildSystemWarnings}

---

## Inline event handlers moved to \`mounted()\`

${eventHandlerSection}

---

## Manual steps checklist

- [ ] Run \`npm install\` in the output directory.
- [ ] Review each \`.dywo\` page and component for correctness.
- [ ] Update any hard-coded asset paths (e.g. \`<img src="images/...">\`) to use DYWO's public asset handling.
- [ ] Replace \`document.querySelector\` usage with DYWO refs or reactive data where possible.
- [ ] If jQuery is in use, audit each jQuery call and convert to native DOM / DYWO APIs.
- [ ] Test routing by running \`dywo dev\`.
- [ ] If you had \`<form>\` elements with server-side targets, wire them up to your API.
- [ ] Remove any dead or duplicated CSS that was inlined from shared stylesheets.

---

## Running the migrated project

\`\`\`bash
cd ${path.basename(outputDir)}
npm install
dywo dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

---

*Generated by DYWO CLI — https://github.com/bluethefoxofficial/dywo-cli*
`;
}

// ---------------------------------------------------------------------------
// Main command
// ---------------------------------------------------------------------------

/**
 * The `dywo migrate` command.
 *
 * @param {Object} options
 * @param {string}  [options.source]   — path to legacy site (default: cwd)
 * @param {string}  [options.output]   — output project path (default: ./dywo-project)
 * @param {boolean} [options.spa]      — convert to SPA mode (skip prompt when provided)
 * @param {boolean} [options.yes]      — skip all interactive prompts, use defaults
 */
async function migrate(options) {
  options = options || {};

  const cwd        = process.cwd();
  const sourceDir  = path.resolve(cwd, options.source || '.');
  const defaultOut = path.resolve(cwd, 'dywo-project');
  let   outputDir  = path.resolve(cwd, options.output || defaultOut);
  let   spaMode    = options.spa;

  // ------------------------------------------------------------------
  // Banner
  // ------------------------------------------------------------------
  console.log('\n' + chalk.bold.blueBright('DYWO Migration Tool'));
  console.log(chalk.gray('Converts a legacy HTML/CSS/JS site into a DYWO project.\n'));

  // ------------------------------------------------------------------
  // Validate source directory
  // ------------------------------------------------------------------
  if (!(await fs.pathExists(sourceDir))) {
    console.error(chalk.red(`Source directory not found: ${sourceDir}`));
    process.exit(1);
  }

  const sourceStat = await fs.stat(sourceDir);
  if (!sourceStat.isDirectory()) {
    console.error(chalk.red(`Source path is not a directory: ${sourceDir}`));
    process.exit(1);
  }

  // ------------------------------------------------------------------
  // Interactive prompts (skip when --yes or explicit flags are given)
  // ------------------------------------------------------------------
  if (!options.yes) {
    const questions = [];

    if (!options.output) {
      questions.push({
        type: 'input',
        name: 'outputDir',
        message: 'Output directory:',
        default: path.relative(cwd, defaultOut) || './dywo-project'
      });
    }

    if (spaMode === undefined || spaMode === null) {
      questions.push({
        type: 'confirm',
        name: 'spa',
        message: 'Convert to SPA mode? (single-page application with client-side routing)',
        default: true
      });
    }

    if (questions.length > 0) {
      const answers = await inquirer.prompt(questions);
      if (answers.outputDir) {
        outputDir = path.resolve(cwd, answers.outputDir);
      }
      if (answers.spa !== undefined) {
        spaMode = answers.spa;
      }
    }
  }

  if (spaMode === undefined) spaMode = true;

  // ------------------------------------------------------------------
  // Sanity-check: don't write inside the source dir
  // ------------------------------------------------------------------
  if (outputDir === sourceDir || outputDir.startsWith(sourceDir + path.sep)) {
    console.error(chalk.red(
      'Output directory must not be inside the source directory.\n' +
      `  source: ${sourceDir}\n  output: ${outputDir}`
    ));
    process.exit(1);
  }

  // ------------------------------------------------------------------
  // Step 1: Analysis
  // ------------------------------------------------------------------
  heading('Analyzing legacy site...');
  console.log(chalk.gray(`  Source: ${sourceDir}`));

  let analysis;
  try {
    analysis = await analyzer.analyze(sourceDir);
  } catch (err) {
    console.error(chalk.red('Analysis failed: ' + err.message));
    process.exit(1);
  }

  const { pages, styles, scripts, assets, detected, buildSystems } = analysis;

  console.log(chalk.white(
    `\nFound ${chalk.bold(pages.length)} HTML page(s), ` +
    `${chalk.bold(styles.length)} CSS file(s), ` +
    `${chalk.bold(scripts.length)} JS file(s), ` +
    `${chalk.bold(assets.length)} asset(s)`
  ));

  if (pages.length === 0) {
    console.log(chalk.yellow('\nNo HTML files found in source directory. Nothing to migrate.'));
    process.exit(0);
  }

  // Report detected frameworks
  if (detected.frameworks.length > 0) {
    warn(`Detected frameworks: ${detected.frameworks.join(', ')} — review MIGRATION.md after conversion`);
  }

  // Report existing build systems
  if (buildSystems && buildSystems.length > 0) {
    warn(`Existing build config(s) found: ${buildSystems.join(', ')} — will not be migrated`);
  }

  // ------------------------------------------------------------------
  // Step 2 & 3: Conversion
  // ------------------------------------------------------------------
  heading('Converting files...');

  // Ensure output directory exists
  await fs.ensureDir(outputDir);

  let conversionResult;
  try {
    conversionResult = await analyzer.convert(analysis, outputDir, {
      spa: spaMode,
      onProgress: (msg) => ok(msg)
    });
  } catch (err) {
    console.error(chalk.red('Conversion failed: ' + err.message));
    if (process.env.DEBUG) console.error(err.stack);
    process.exit(1);
  }

  const { report } = conversionResult;

  // Show shared components
  if (report.sharedComponentsDetected.length > 0) {
    heading('Shared components detected:');
    report.sharedComponentsDetected.forEach(c => ok(`${c}  →  src/components/${c}.dywo`));
  }

  // ------------------------------------------------------------------
  // Step 4: Copy assets
  // ------------------------------------------------------------------
  if (assets.length > 0) {
    heading(`Copying ${assets.length} asset(s)...`);
    let copied = 0;
    let skipped = 0;
    for (const asset of assets) {
      const src  = path.join(sourceDir, asset);
      const dest = path.join(outputDir, 'public', asset);
      try {
        await fs.ensureDir(path.dirname(dest));
        await fs.copy(src, dest);
        copied++;
      } catch {
        skipped++;
      }
    }
    if (copied > 0)  ok(`Copied ${copied} asset(s) to public/`);
    if (skipped > 0) warn(`Skipped ${skipped} asset(s) (could not be read)`);
  }

  // ------------------------------------------------------------------
  // Step 5: Write MIGRATION.md
  // ------------------------------------------------------------------
  const migrationMd = buildMigrationMd(report, sourceDir, outputDir, spaMode);
  await fs.writeFile(path.join(outputDir, 'MIGRATION.md'), migrationMd, 'utf8');

  // ------------------------------------------------------------------
  // Summary
  // ------------------------------------------------------------------
  heading(`Generated DYWO project at ${path.relative(cwd, outputDir) || outputDir}`);
  console.log('');

  report.writtenPages.forEach(p => info(p));
  if (report.writtenComponents.length > 0) {
    report.writtenComponents.forEach(c => info(c));
  }
  info('src/main.dywo');
  info('public/index.html');
  info('dywo.config.js');
  info('package.json');
  info('.gitignore');
  info('MIGRATION.md');

  console.log('');
  ok('Migration notes saved to MIGRATION.md');

  // ------------------------------------------------------------------
  // Next steps
  // ------------------------------------------------------------------
  console.log('\n' + chalk.bold('Next steps:'));
  const relOut = path.relative(cwd, outputDir) || outputDir;
  console.log(chalk.cyan(`  cd ${relOut}`));
  console.log(chalk.cyan('  npm install'));
  console.log(chalk.cyan('  dywo dev'));
  console.log('');
  console.log(chalk.gray('Review MIGRATION.md for items requiring manual attention.'));
  console.log('');
}

module.exports = migrate;
